# This file was generated by the {rix} R package v0.6.0 on 2024-04-14
# with following call:
# >rix(r_ver = "a0c9e3aee1000ac2bfb0e5b98c94c946a5d180a9",
#  > r_pkgs = c("quarto"),
#  > system_pkgs = "quarto",
#  > git_pkgs = list(package_name = "rix",
#  > repo_url = "https://github.com/b-rodrigues/rix",
#  > branch_name = "master",
#  > commit = "76d1bdd03d78589d399b4b9d473ecde616920a82"),
#  > tex_pkgs = c("amsmath",
#  > "orcidlink",
#  > "tcolorbox"),
#  > ide = "other",
#  > project_path = path_default_nix,
#  > overwrite = TRUE)
# It uses nixpkgs' revision a0c9e3aee1000ac2bfb0e5b98c94c946a5d180a9 for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/a0c9e3aee1000ac2bfb0e5b98c94c946a5d180a9.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) quarto;
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "rix";
    src = pkgs.fetchgit {
      url = "https://github.com/b-rodrigues/rix";
      branchName = "master";
      rev = "76d1bdd03d78589d399b4b9d473ecde616920a82";
      sha256 = "sha256-ZGwNG2uK/G8Y8S7sTGzlhsnN682XDCLCd4ZoLoev7Mw=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) codetools httr jsonlite sys;
    };
  }) ];
 tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small amsmath orcidlink tcolorbox;
});
 system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix quarto;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs tex system_packages  ];
      
  }
